### ISSUE TITLE
[경준] 피드백

### ISSUE THREAD

**Issue by ryanpark91** [academey/ridi-new-entrant-web#1]
1. 도서를 대여할 때 프론트에서 `endAt`을 넘겨주는 것이 아니라 백엔드에서 계산해서 프론트에 알려주는 것이 맞는 것 같다

   1. endAt을 조작해서 요청할 수 있음

2. endAt을 datatime 형식이 아닌 다른 값을 넘기면 sql 쿼리가 response로 넘어옴

   1. ```json
      {"status":"fail","message":"(conn=31, no: 1292, SQLState: 22007) Incorrect datetime value: '213123-01-01 09:00:00.000' for column `ridi_entrant`.`BookReservation`.`endAt` at row 1\nsql: INSERT INTO `BookReservation` (`id`,`userId`,`bookId`,`endAt`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?); - parameters:[14,12,'213123-01-01 09:00:00.000','2019-07-02 11:24:23.815','2019-07-02 11:24:23.815']"}
      ```

3. 현재 borrow할 때 endAt이 프론트에서 `2019-06-01`으로 넘어가고 있음

   1. `/src/client/api/index.ts` 에서 하드 코딩 되어 있음
   2. 나중에 이런 실수 없도록 TODO 주석 남겨놓도록 하면 좋을 듯

4. [POST] `http://54.180.137.113:8080/api/books/10/borrow` 와 같이 없는 도서에 대한 대여 가능하도록 되어 있음

**Comment by academey** [comment]
직접 디버깅까지.. 리뷰 감사합니다

**Comment by academey** [comment]
1. 저는 책 대여를 2주 이내로 유저가 선택해서 하는거라고 생각해서 endAt 필드를 만들어놨습니다. 예를 들어 2일만 빌리고 싶으면 2일 후 등으로 입력받으려고 했습니다. 프론트에도 입력값 검증을 넣으면 프론트에서 요청을 날리도록 만들어도 괜찮지 않을까요??

2. 아앗.. 요 부분은 property-validator 에서 제가 생각하지 못했던 부분이었습니다. isISO8601 검증을 넣으면 해결될 것 같습니다. 감사합니다.

3. 이 부분은 현재 클라이언트에 endAt을 입력하는 부분이 없어 추후에 하겠다는 생각으로 하드코딩했었습니다. 말씀해주신대로 TODO 를 꼭 붙이도록 하겠습니다.

4. 이 부분도 마찬가지로 검증을 하지 못했습니다. 검증 로직을 추가하도록 하겠습니다!

**Comment by ryanpark91** [comment]
1. 
특정 대여기간이 고정이라면 백엔드에서 하는게 좋다고 말씀드린거고요.
현준님 말씀대로 프론트에서 날짜를 조절 가능하다고 하면, 백엔드에선 과거 날짜가 아닌지만 체크하고 유효한 date인지만 체크하도록 하면 될 것 같습니다 👍

**Comment by academey** [comment]
넵! https://github.com/academey/ridi-new-entrant-web/commit/6ee7ea50dcf0f5e7e6e8ad8251f0d998533a8b54 에서 2, 3, 4 이슈들 해결하고 테스트 케이스 추가했습니다. 감사합니다.
