### ISSUE TITLE
[아연] 피드백

### ISSUE THREAD

**Issue by AYONC** [academey/ridi-new-entrant-web#2]
### Routers에서
- init 두번 불림 constructor 에서 한번 생성후 한번 더 호출
- process.env wrapping 해서 사용하기
- http response code 상수화 enum 해서 사용하기
-  반복되는 패턴의 코드를 더 줄여보기
	-  dot notation 이 반복되는 경우
```js
res.status(xx).json(response)
const handleSuccess = (res, data) => res.status(code).json(makeSuccessResponse(data));
return handleSuccess(res, data);
const handleFailure = (res, err, code = 400) => res.status(code).json(makeFailResponse(data));
return handleFailure(res, err);

const result = { user, token, message: ‘가입 성공했습니다.’ };
return handleSuccess(res, result, 201);
```
- makeSuccessResponse 에서 status를 주는 것은 result에 포함 시키려고 추가된 것인가요
- db 객체에 직접 접근해서 요청을 처리하고 있는데 중간 레이어가 있으면 에러처리가 더 용이 하고 코드가 보기 좋을것 같습니다

### 질문!
-  assertAll 매 메서드 마다 사용하고 있는데 미들웨어나 데코레이션으로 처리하는 방법은 없는지
- 싱글턴인데 static 으로 만들지 않고 만든 이유

**Comment by academey** [comment]
오 자세한 피드백 감사드립니다!!

**Comment by academey** [comment]
1. init 두번 불림 constructor 에서 한번 생성후 한번 더 호출
-> constructor 에서 호출하도록 변경했습니다.

2. process.env wrapping 해서 사용하기
-> server/utils/envChecker.ts 를 만들어서 사용하게 되었습니다.

3. http response code 상수화 enum 해서 사용하기
-> src/server/routes/constants.ts 를 만들어서 상수화 시켰습니다.

4. 반복되는 패턴의 코드를 더 줄여보기 & dot notation 이 반복되는 경우
-> makeFailResponse 등의 함수를 만들어서 반복되는 형태를 간략화 시켰습니다.

5. makeSuccessResponse 에서 status를 주는 것은 result에 포함 시키려고 추가된 것인가요
-> 질문을 이해하지 못했습니다.. 😢 

6. db 객체에 직접 접근해서 요청을 처리하고 있는데 중간 레이어가 있으면 에러처리가 더 용이 하고 코드가 보기 좋을것 같습니다
-> Service 레이어를 추가했습니다. 확실히 쿼리가 들어가는 것보다 훨씬 관리 & 보기 좋아졌습니다.

7. assertAll 매 메서드 마다 사용하고 있는데 미들웨어나 데코레이션으로 처리하는 방법은 없는지
각 라우터의 메소드마다 필요한 파라미터와 조건들이 달라서 공통으로 처리하는 방법은 없어 보입니다.

8. 싱글턴인데 static 으로 만들지 않고 만든 이유
라우터와 App 을 싱글톤 클래스로 변경했습니다! 아무래도 함수별로 관리하는게 보기 용이해서 클래스 형태는 유지했습니다.
